language: python
# command to install dependencies
install: make
# command to run tests
script:
  - make test-readme
  - make ci
after_success:
  - codecov
cache: pip
jobs:
  include:
    - stage: test
      python: '3.6'
    - stage: test
      python: '3.7'
    - stage: test
      python: '3.8'
